# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c4f53f4fee27d1b03a72d7aa31adb4dc1ab266d5c5dd34de0a68ebe152ec7bc35999ade7120771cb9c567f109b61d9a777d05004e2c8b971ec0d22d751e3244

test:
  secret_key_base: e2cc12bdc18b3f0694fe450b56b82440f8b915b1d56287b42ea0a3cad7feb84890db930bdcc1840bc18b03dcccb38b90f8579fea189d02b9ddfd42e4410b229c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
